version: "3.9"
services:
  postgres:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=crawler
      - POSTGRES_DB=crawler
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - node-network

  crawler:
    build: .
    container_name: crawler
    image: crawler:latest
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://crawler:crawler@localhost:5432/crawler?schema=public
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - node-network

volumes:
  postgres:

networks:
  node-network:
    driver: bridge
